# Generated by Django 4.0.6 on 2022-09-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commentpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='comment_id',
            new_name='post_id',
        ),
    ]
