# Generated by Django 4.0.6 on 2022-09-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_comment_id_commentpost_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
